// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_testes_estudo/test/contador_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_testes_estudo/data/contador_database.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ContadorDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockContadorDatabase extends _i1.Mock implements _i2.ContadorDatabase {
  MockContadorDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> abrirBanco() => (super.noSuchMethod(
        Invocation.method(
          #abrirBanco,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> fecharBanco() => (super.noSuchMethod(
        Invocation.method(
          #fecharBanco,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> salvar(int? valor) => (super.noSuchMethod(
        Invocation.method(
          #salvar,
          [valor],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> ler() => (super.noSuchMethod(
        Invocation.method(
          #ler,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> remover() => (super.noSuchMethod(
        Invocation.method(
          #remover,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
